export enum USER_ACTION_TYPES {
  SET_CURRENT_USER = 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION = 'user/CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START = 'user/SET_CURRENT_USER',
  EMAIL_SIGN_IN_START = 'user/EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS = 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED = 'user/SIGN_IN_FAILED',
  SING_UP_START = 'user/SING_UP_START',
  SING_UP_SUCCESS = 'user/SING_UP_SUCCESS',
  SING_UP_FAILED = 'user/SING_UP_FAILED',
  SING_OUT_START = 'user/SING_OUT_START',
  SING_OUT_SUCCESS = 'user/SING_OUT_SUCCESS',
  SING_OUT_FAILED = 'user/SING_OUT_FAILED',
}
